/** Fixed, human-written safety copy. Never generated by a model. */
export const EMERGENCY_NOTICE =
  'If this could be an emergency, please contact your local emergency services (dial 112 in India) or go to the nearest emergency department now. FlowCare is a hospital directory and cannot assess how urgent a situation is.';

export const SCOPE_NOTICE =
  "FlowCare's assistant helps you find and compare hospitals and appointments. It does not diagnose, recommend treatment, or judge how urgent your situation is.";
